export const mockHotels = [
    {
        id: 1,
        name: 'Hotel Taj Palace',
        address: 'Delhi, India',
        price: 10000,
        image_url: '/Hotel-taj-delhi.jpg',
    },
    {
        id: 2,
        name: 'Leela Palace',
        address: 'Bengaluru, India',
        price: 12000,
        image_url: '/Leela-Palace-Bengaluru.jpg',
    },
    {
        id: 3,
        name: 'Oberoi Hotel',
        address: 'Mumbai, India',
        price: 15000,
        image_url: '/Oberoi-Hotel.jpg',
    },
    {
        id: 4,
        name: 'ITC Grand Bharat',
        address: 'Gurugram, India',
        price: 22000,
        image_url: '/ITC-Bharat.jpg',
    },
    {
        id: 5,
        name: 'The Oberoi Udaivilas',
        address: 'Udaipur, India',
        price: 35000,
        image_url: '/Udaivilas.jpg',
    },
    {
        id: 6,
        name: 'The Leela Mumbai',
        address: 'Mumbai, India',
        price: 18000,
        image_url: '/Leela.jpg',
    },
    {
        id: 7,
        name: 'Radisson Blu Resort',
        address: 'Alibaug, India',
        price: 14000,
        image_url: '/alibagh.jpg',
    },
    {
        id: 8,
        name: 'JW Marriott Hotel',
        address: 'New Delhi, India',
        price: 25000,
        image_url: '/JW.jpg',
    },
    {
        id: 9,
        name: 'The Taj Mahal Palace',
        address: 'Mumbai, India',
        price: 30000,
        image_url: '/taj.jpg',
    },
    {
        id: 10,
        name: 'The Leela Kovalam',
        address: 'Kovalam, India',
        price: 20000,
        image_url: '/kovalam.jpg',
    },
    {
        id: 11,
        name: 'The Park Chennai',
        address: 'Chennai, India',
        price: 12000,
        image_url: '/park.jpg',
    },
    {
        id: 12,
        name: 'Park Hyatt Chennai',
        address: 'Chennai, India',
        price: 22000,
        image_url: '/hyatt.jpg',
    },
    {
        id: 13,
        name: 'The Westin Goa',
        address: 'Goa, India',
        price: 15000,
        image_url: '/goawest.jpg',
    },
    {
        id: 14,
        name: 'Taj Exotica Resort & Spa',
        address: 'Goa, India',
        price: 27000,
        image_url: '/tajexotica.jpg',
    },
    {
        id: 15,
        name: 'The Imperial New Delhi',
        address: 'New Delhi, India',
        price: 35000,
        image_url: '/Imperial.jpg',
    },
    {
        id: 16,
        name: 'Hyatt Centric MG Road',
        address: 'Bengaluru, India',
        price: 20000,
        image_url: '/Hyattmg.jpg',
    },
    {
        id: 17,
        name: 'Sheraton Grand Bangalore',
        address: 'Bengaluru, India',
        price: 16000,
        image_url: '/Grand.jpg',
    },
    {
        id: 18,
        name: 'The Trident Udaipur',
        address: 'Udaipur, India',
        price: 22000,
        image_url: '/trident.jpg',
    },
    {
        id: 19,
        name: 'Radisson Blu Plaza Delhi',
        address: 'New Delhi, India',
        price: 13000,
        image_url: '/bluplaza.jpg',
    },
    {
        id: 20,
        name: 'The Lalit Ashok Bangalore',
        address: 'Bengaluru, India',
        price: 21000,
        image_url: '/lalit.jpg',
    },
    {
        id: 21,
        name: 'Le Meridien Jaipur Resort & Spa',
        address: 'Jaipur, India',
        price: 17000,
        image_url: '/le-meridian.jpg',
    },
    {
        id: 22,
        name: 'The Westin Hyderabad Mindspace',
        address: 'Hyderabad, India',
        price: 21000,
        image_url: '/Westin.jpg',
    },
    {
        id: 23,
        name: 'Radisson Blu Hotel, Varanasi',
        address: 'Varanasi, India',
        price: 12000,
        image_url: '/varanasi.jpg',
    },
    {
        id: 24,
        name: 'The Oberoi Amarvilas',
        address: 'Agra, India',
        price: 35000,
        image_url: '/Amarvilas.jpg',
    },
    {
        id: 25,
        name: 'Holiday Inn Resort Goa',
        address: 'Goa, India',
        price: 13000,
        image_url: '/holiday.jpg',
    },
];